Repository ucsb-cs156-s24/proj-organic-s24-5pm-4, pull requests merged in 2024-05, with the labels that each got.

#7 Added Option to Enable/Disable Swagger on Navbar
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: 5

#12 Upgrading Backend to Spring-Boot 3.2.5
  pom.xml
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/FrontendProxyController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
  src/main/java/edu/ucsb/cs156/organic/entities/Course.java
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/entities/Staff.java
  src/main/java/edu/ucsb/cs156/organic/entities/Student.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/main/java/edu/ucsb/cs156/organic/entities/UserEmail.java
  src/main/java/edu/ucsb/cs156/organic/entities/jobs/Job.java
  src/main/resources/application-production.properties
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/services/GrantedAuthoritiesServiceTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/MockCurrentUserServiceImpl.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/TestConfig.java
Labels: 20

#10 Completion of Expose-Commit
  Dockerfile
  pom.xml
  src/main/java/edu/ucsb/cs156/organic/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/organic/services/SystemInfoServiceImplTests.java
Labels: sp24-5pm-4

#22 Refactor the Course Form
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/stories/components/Courses/CoursesForm.stories.js
  frontend/src/stories/pages/CoursesCreatePage.stories.js
  frontend/src/stories/pages/CoursesEditPage.stories.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
  frontend/src/tests/pages/CoursesCreatePage.test.js
  frontend/src/tests/pages/CoursesEditPage.test.js
Labels: NOTE-Depends on another PR
